version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: billwise-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - billwise-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: billwise-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - billwise-node-modules:/app/node_modules
    networks:
      - billwise-net
    command: >
      sh -c "npx prisma generate && npm run dev"

volumes:
  pgdata:
  billwise-node-modules:

networks:
  billwise-net:
