version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: billwise-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billwise_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - billwise-net

  app:
    container_name: billwise-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/billwise_dev
      NODE_ENV: development
    depends_on:
      - postgres
    volumes:
      - .:/app:delegated
      - /app/node_modules
    networks:
      - billwise-net
    command: >
      sh -c "npx prisma migrate dev --name init && npm run dev"

volumes:
  pgdata:

networks:
  billwise-net:
